#!/usr/bin/env bash

# git hook to run a command after `git pull` if a specified file was changed
# Initialize the scripts in /.githooks with `git config core.hooksPath .githooks`

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

check_run yarn.lock "yarn install"
check_run composer.lock "composer install"
