contao:
  localconfig:
    licenseAccepted: true
    disableCron: true
    installPassword: '%env(INSTALL_PASSWORD)%'
    adminEmail: '%env(ADMIN_EMAIL)%'
    dateFormat: "d.m.Y"
    datimFormat: "d.m.Y H:i"
    timeZone: 'Europe/Berlin'

framework:
  assets:
    packages:
      contao_backend:
        json_manifest_path: '%kernel.project_dir%/web/layout/backend/manifest.json'

imports:
  - { resource: services.yml }
